### ISSUE TITLE
Feature: a web implementation of XKeysWatcher

### ISSUE THREAD

**Issue by loucadufault** [SuperFlyTV/xkeys#104]
The same use case for XKeysWatcher exists in browser-based environments as for the node implementation. The trouble is that the current node implementation relies on node specific packages.

I have made a pure-polling implementation that is compatible with the browser, opening this ticket to gauge interest/viability before opening a PR. Thanks!

**Comment by nytamin** [comment]
Yeah, this would be a good feature to add to the browser version as well! I'd gladly accept a PR! 👍
