### ISSUE TITLE
this.deviceType.banks 2 on console when setting backlightintensity

### ISSUE THREAD

**Issue by laurensvane** [SuperFlyTV/xkeys#25]
When i set the backlightintensity i get a console.log message, it looks like a random console.log has been left in the sourcecode:

https://github.com/SuperFlyTV/xkeys/blob/8f06cc4681e691a8513c911dbc9be8b43e2e4d0b/src/xkeys.ts#L337

Or is this intentional?

**Comment by nytamin** [comment]
Thanks for bringing it up. It looks like some leftover debug trace. It can be ignored for now and I'll push an update in the next few days that'll remove it.

**Comment by nytamin** [comment]
This has been fixed in version `1.1.1`
