### ISSUE TITLE
no matching member function for call to 'NewInstance'

### ISSUE THREAD

**Issue by johnsturgeon** [SuperFlyTV/xkeys#6]
Looks like xkeys is no longer compatible with latest node (v11)

**Comment by nytamin** [comment]
This is most probably an issue with [node-hid](https://github.com/node-hid/node-hid#supported-node-versions), as v11.x isn't listed as a supported version, so the discussion should probably be taken up over there to implement the support.

I'll gladly accept a pull-request with a fix, in the meantime I suggest you try with using one of the LTS-versions (8.x or 10.x).

**Comment by johnsturgeon** [comment]
Thanks, I reverted back to Node 9.11.1 and that fixed the problem
