### ISSUE TITLE
XK-24 EEPROM retaining code?

### ISSUE THREAD

**Issue by will-riley** [SuperFlyTV/xkeys#84]
Having an issue with an XK-24 where it's hanging onto previous programming while I'm trying to update code - how do I overwrite the non-volatile internal code while developing? Not seeing a function for that...or is it just my keypad? Thanks for any pointers!

**Comment by nytamin** [comment]
There are certain functions that aren't implemented in this library, like firmware updates or setting macros/keyboard functions. Perhaps you might find something in the official software? https://xkeys.com/software.html

**Comment by michaelhatPIengineering** [comment]
Writing macros or erasing them can lead to bricking the device if not done properly. So to clear the memory of previous codes we recommend using a utility provided by P.I. Engineering (X-keys). https://xkeys.com/software/softwarewindows/softwaremacroworkshw.html
X-keys basic setup is one utility that will do that. 
Usually, this library is used for direct access and control of X-keys devices and would not be used with them in their "emulation modes" where the macros are used. But there is nothing to prevent using them in a  blended mode.
